# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.6.5

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:11.5
  - redis:5.0

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python3 -V                                   # Print out python version for debugging
  - pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
  - export DJANGO_SETTINGS_MODULE=conf.development.settings

test:
  only:
  - master

  variables:
    SECRET_KEY: 'p8skrou5o+_i36sq^54+_z%ufq_i)cg3vz34efqa+2rb5$g&mi'
    DATABASE_HOST: 'postgres'
    DATABASE_PORT: '5432'
    DATABASE_NAME: 'k8sdjango_development'
    DATABASE_USER: 'postgres'
    DATABASE_PASSWORD: 'postgres'
    REDIS_URL: 'redis://redis:6379/0'

  script:
  - pytest --verbose
