version: '3'
services:
  db:
    image: postgres:11.5
    container_name: k8sdjango-postgres
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
    environment:
      POSTGRES_USER: k8sdjango_production
      POSTGRES_PASSWORD: b8n2maLRb7EUyv8c
      POSTGRES_DB: k8sdjango_production
    ports:
      - '5432:5432'
    volumes:
      - ./compose/postgres_data:/var/lib/postgresql/data
      - ./compose/postgresql.conf:/usr/local/etc/postgresql/11/postgresql.conf
      - ./compose/pg_hba.conf:/usr/local/etc/postgresql/11/pg_hba.conf

  redis:
    image: redis:5.0.5
    container_name: k8sdjango-redis
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 500M
    ports:
     - '6379:6379'
    volumes:
      - ./compose/redis_data:/data
    depends_on:
      - "db"

  rabbitmq:
    image: rabbitmq:3.7.17
    container_name: k8sdjango-rabbitmq
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 1500M
    # environment:
    #   RABBITMQ_DEFAULT_VHOST: /
    #   RABBITMQ_DEFAULT_USER: k8sdjangovhost
    #   RABBITMQ_DEFAULT_PASS: b8n2maLRb7EUyv8c
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15674:15674'
    volumes:
      - ./compose/rabbitmq_data:/var/lib/rabbitmq
      - ./compose/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
    depends_on:
      - "redis"

  nginx:
    image: nginx:1.16
    container_name: k8sdjango-nginx
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d
      - ./compose/static:/k8sdjango/static
      - ./compose/nginx_log:/var/log/nginx
    depends_on:
      - "web"

  web:
    build: .
    image: django-docker-web
    container_name: k8sdjango-web
    command: sh -c "wait-for db:5432 && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn k8sdjango.wsgi --workers 5 --threads=2 --bind 0.0.0.0:8080"
    environment:
      DJANGO_SETTINGS_MODULE: conf.production.settings
      TZ: Asia/Shanghai
    volumes:
      - ./compose/static:/k8sdjango/static
    depends_on:
      - "db"
    expose:
      - "8080"

  celery_worker:
    image: django-docker-web
    container_name: k8sdjango-celery_worker
    command: sh -c "wait-for rabbitmq:5672 && celery -A apps.celeryconfig worker --loglevel=info --autoscale=4,2"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 500M
    environment:
      DJANGO_SETTINGS_MODULE: conf.production.settings
      TZ: Asia/Shanghai
    depends_on:
      - "db"
      - "redis"
      - "rabbitmq"
      - "web"
      - "nginx"

  celery_beat:
    image: django-docker-web
    container_name: k8sdjango-celery_beat
    command: sh -c "wait-for rabbitmq:5672 && celery -A apps.celeryconfig beat --loglevel=info"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 500M
    environment:
      DJANGO_SETTINGS_MODULE: conf.production.settings
      TZ: Asia/Shanghai
    depends_on:
      - "db"
      - "redis"
      - "rabbitmq"
      - "web"
      - "nginx"
      - "celery_worker"
