# Generated by Django 2.1.10 on 2019-10-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('mobile', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': '采购人',
                'verbose_name_plural': '采购人',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='用户名+时间戳字符串', max_length=255)),
                ('sn', models.CharField(max_length=255)),
                ('status', models.TextField(choices=[('1', '现货'), ('2', '待采购'), ('3', '采购完成')], default='1', max_length=1)),
                ('seller_note', models.TextField(blank=True, default='')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_broker_orders', to='agents.Broker')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='用户名+时间戳字符串', max_length=255)),
                ('sn', models.CharField(max_length=255)),
                ('status', models.TextField(choices=[('1', '创建成功'), ('2', '手动关闭'), ('3', '接单中'), ('4', '接单完成')], default='1', max_length=1)),
                ('buyer_note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '需求订单',
                'verbose_name_plural': '需求订单',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('nums', models.IntegerField(default=1)),
                ('except_price', models.DecimalField(decimal_places=2, help_text='期待价格', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='总金额', max_digits=8)),
                ('broker_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_order_order_product', to='agents.BrokerOrder')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_order_products', to='agents.CustomerOrder')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='用户名+时间戳字符串', max_length=255)),
                ('sn', models.CharField(max_length=255)),
                ('status', models.TextField(choices=[('1', '创建成功-待支付'), ('2', '支付超时-订单关闭'), ('3', '手动关闭订单'), ('4', '支付完成-待发货'), ('5', '已发货-待收货'), ('6', '已收货-待评价'), ('7', '已评价-交易完成')], default='1', max_length=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True, default='')),
                ('express_type', models.TextField(choices=[('1', '快递'), ('2', '自提')], default='1', max_length=1)),
                ('closed_datetime', models.DateTimeField(blank=True, null=True)),
                ('seller_packaged_datetime', models.DateTimeField(blank=True, null=True)),
                ('received_datetime', models.DateTimeField(blank=True, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('payment_sn', models.CharField(blank=True, default='', max_length=255)),
                ('payment_datetime', models.DateTimeField(blank=True, null=True)),
                ('customer_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order_shipping_order', to='agents.CustomerOrder')),
            ],
            options={
                'verbose_name': '出货订单',
                'verbose_name_plural': '出货订单',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StandardProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('available_in', models.CharField(max_length=255)),
                ('price_range', models.CharField(max_length=255)),
                ('purchase_price', models.CharField(max_length=255)),
                ('header_image', models.URLField()),
            ],
            options={
                'verbose_name': '标准商品',
                'verbose_name_plural': '标准商品',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='standard_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_product_order_products', to='agents.StandardProduct'),
        ),
    ]
