# Generated by Django 2.1.10 on 2019-10-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('mobile', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': '买家',
                'verbose_name_plural': '买家',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
